# Generated by Django 2.1.7 on 2019-02-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190214_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postindexpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='postindexpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page'),
        ),
    ]
